name: build and test

on:
  push:
  pull_request:
    branches: [main]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core App
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Install Dependencies
      run: dotnet restore -p:FullTargets=false

    - name: Build
      run: dotnet build --no-restore -p:FullTargets=false

    - name: Test
      run: dotnet test --no-restore --blame-hang-timeout 1m -p:FullTargets=false
